//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCQ_Etqan.Webparts.Home.WorkShopDetails
{


    public partial class WorkShopDetailsUserControl
    {
    }
}
